//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Reg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reg()
        {
            this.Task1 = new HashSet<Task1>();
        }
    
        public int RegID { get; set; }

        [Required(ErrorMessage ="please Enter FullName")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "please Enter Username which is max value 8 and min 3")]
        [StringLength(8,MinimumLength =3)]
        public string UserName { get; set; }
        [StringLength(10,MinimumLength =3)]
        [Required(ErrorMessage = "please Enter Password which is max value 10 and min 3")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "please Enter ConfirmPassword")]
        [Compare("Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "please Enter Dateofirth")]
        public string DateOFBirth { get; set; }

        [Required(ErrorMessage = "please Enter Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "please Enter MobileNo")]
        public string MobileNo { get; set; }
        [Required(ErrorMessage = "please Enter EmailID")]
        [RegularExpression(".+\\@.+\\..+")]
        public string EmailID { get; set; }
        [Display(Name ="Terms & condition")]
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task1> Task1 { get; set; }
    }
}
