//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Task1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task1()
        {
            this.Ans = new HashSet<An>();
        }
    
        public int TaskID { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "please Enter Date")]
        public string Date { get; set; }
        public int RegID { get; set; }
        public int CourseID { get; set; }
        [Required(ErrorMessage = "please Enter Question")]
        public string Question { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<An> Ans { get; set; }
        public virtual Course Course { get; set; }
        public virtual Reg Reg { get; set; }
    }
}
